# Generated by Django 5.0.3 on 2024-04-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crystal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('properties', models.TextField(max_length=250)),
                ('shakra', models.CharField(max_length=50)),
                ('mohs', models.IntegerField()),
            ],
        ),
    ]
