# Generated by Django 5.0.3 on 2024-04-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crystal',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
