# Generated by Django 5.0.3 on 2024-04-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_collection_remove_crystal_mohs_remove_crystal_shakra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crystal',
            name='zodiac',
            field=models.CharField(blank=True),
        ),
    ]
