# Generated by Django 5.0.3 on 2024-04-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_crystal_zodiac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crystal',
            name='collections',
        ),
        migrations.AddField(
            model_name='collection',
            name='crystal',
            field=models.ManyToManyField(to='main_app.crystal'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.URLField(),
        ),
    ]
