# Generated by Django 5.0.3 on 2024-04-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_crystal_collections_collection_crystal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='crystal',
        ),
        migrations.AddField(
            model_name='crystal',
            name='collections',
            field=models.ManyToManyField(to='main_app.collection'),
        ),
    ]
